name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for x86
        run: make build

      - name: List built binary
        run: ls -l bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nats-ws-gateway-and-server-linux-amd64
          path: bin/nats-ws-gateway-and-server

      - name: Create GitHub Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: bin/nats-ws-gateway-and-server
          body: |
            Automated release of nats-ws-gateway-and-server for version ${{ github.ref_name }}.
