name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Use the specific Go version from go.mod
          go-version: '1.24.2'

      - name: Build for ${{ matrix.goarch }}
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          make build

      - name: Rename and list built binary
        run: |
          mv bin/nats-ws-gateway-and-server bin/nats-ws-gateway-and-server-${{ matrix.goarch }}
          ls -l bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nats-ws-gateway-and-server-${{ matrix.goarch }}
          path: bin/nats-ws-gateway-and-server-${{ matrix.goarch }}

      - name: Create GitHub Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/') && matrix.goarch == 'amd64'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/nats-ws-gateway-and-server-amd64
            bin/nats-ws-gateway-and-server-arm64
          body: |
            Automated release of nats-ws-gateway-and-server for version ${{ github.ref_name }}.
